"""Harness-neutral YAML agent templates and per-harness converters.

The canonical agent definitions live as structured YAML under
``src/dftracer_agents/.agents/agents/*.yaml`` — ONE git-tracked template per
agent, with clean tags instead of any harness's frontmatter dialect:

.. code-block:: yaml

    name: dftracer-analyzer
    description: >-
      Pipeline stage 5. Runs dfanalyzer over compacted traces ...
    model_level: level_3        # resolved per harness via active-models.json
    effort: low                 # claude-only hint; others ignore it
    isolation: worktree         # claude-only hint; others ignore it
    tools:                      # neutral names; converters reshape per dialect
      - Read
      - Bash
      - mcp__dftracer__analyze
    skills:
      - dftracer-context-economy
    sections:                   # ordered prompt body
      - title: Load your plan section first
        body: |
          The pipeline planner has written ...
      - include: self-learning  # shared block from common-sections.yaml

Shared prose that used to be pasted into every agent (self-learning rules,
profiling brackets, context economy, privacy) lives once in
``common-sections.yaml`` and is pulled in with ``- include: <name>`` entries,
so a lesson that changes a shared rule is a one-file edit.

Converters render the template into each harness's on-disk dialect:

============  =============================  ==========================================
harness       output path                    frontmatter dialect
============  =============================  ==========================================
claude        .claude/agents/<name>.md       model: <class>; tools: comma string
opencode      .opencode/agents/<name>.md     mode: subagent; model: provider/id;
                                             tools: {"*": false, <tool>: true} map
copilot       .github/agents/<name>.agent.md tools: YAML list; mcp as server/tool
============  =============================  ==========================================

Rendered files are build artifacts: gitignored, stamped with a generation
marker, and regenerated by ``ensure_agents_setup`` / the ``agents_sync`` MCP
tool. Never edit them — edit the YAML template and re-sync.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

HARNESSES = ("claude", "opencode", "copilot")

GEN_MARKER_FMT = (
    "# generated-by: dftracer-agents ({harness}) — edit the YAML template under "
    "src/dftracer_agents/.agents/agents/, not this file; then run agents_sync"
)

# Where each harness discovers agents, relative to the workspace root, and the
# filename pattern it requires.
HARNESS_OUTPUT = {
    "claude": (".claude/agents", "{name}.md"),
    "opencode": (".opencode/agents", "{name}.md"),
    "copilot": (".github/agents", "{name}.agent.md"),
}

# Built-in tool-name mapping per harness. Claude names are the neutral form
# (this project's tools: lists were written for Claude Code). MCP tools use
# the mcp__<server>__<tool> neutral form and are reshaped per harness.
_OPENCODE_BUILTIN = {
    "Read": "read", "Write": "write", "Edit": "edit", "Bash": "bash",
    "Grep": "grep", "Glob": "glob", "WebFetch": "webfetch", "Task": "task",
    "TodoWrite": "todowrite",
}
_COPILOT_BUILTIN = {
    "Read": "read", "Write": "edit", "Edit": "edit", "Bash": "shell",
    "Grep": "search", "Glob": "search", "WebFetch": "fetch",
}

_MCP_RE = re.compile(r"^mcp__([^_]+(?:_[^_]+)*?)__(.+)$")


class TemplateError(ValueError):
    """A YAML agent template is malformed."""


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def templates_dir() -> Path:
    """The bundled YAML template directory (canonical, git-tracked source)."""
    d = Path(__file__).resolve().parent / ".agents" / "agents"
    if not d.is_dir():
        raise FileNotFoundError(f"Bundled agent templates directory not found at {d}.")
    return d


def common_sections_path(base: Optional[Path] = None) -> Path:
    return (base or templates_dir()) / "common-sections.yaml"


def load_common_sections(base: Optional[Path] = None) -> Dict[str, Dict[str, str]]:
    """Load the shared section library: name -> {title, body}."""
    path = common_sections_path(base)
    if not path.is_file():
        return {}
    data = yaml.safe_load(path.read_text()) or {}
    sections = data.get("sections", {})
    if not isinstance(sections, dict):
        raise TemplateError(f"{path}: top-level 'sections' must be a map")
    out: Dict[str, Dict[str, str]] = {}
    for name, entry in sections.items():
        if not isinstance(entry, dict) or "body" not in entry:
            raise TemplateError(f"{path}: section '{name}' must be a map with a 'body'")
        out[str(name)] = {"title": str(entry.get("title", name)), "body": str(entry["body"])}
    return out


def load_template(path: Path, common: Optional[Dict[str, Dict[str, str]]] = None) -> Dict[str, Any]:
    """Load and validate one agent template; resolve ``include:`` sections.

    Returns the template dict with ``sections`` normalized to a list of
    ``{title, body}`` dicts (includes expanded, order preserved).
    """
    data = yaml.safe_load(path.read_text())
    if not isinstance(data, dict):
        raise TemplateError(f"{path}: template must be a YAML map")
    for key in ("name", "description", "model_level", "sections"):
        if key not in data:
            raise TemplateError(f"{path}: missing required key '{key}'")
    if not re.fullmatch(r"level_[0-9]+", str(data["model_level"])):
        raise TemplateError(f"{path}: model_level must look like level_N, got {data['model_level']!r}")
    for key in ("tools", "skills"):
        value = data.get(key, [])
        if not isinstance(value, list) or not all(isinstance(t, str) for t in value):
            raise TemplateError(f"{path}: '{key}' must be a list of strings")

    if common is None:
        common = load_common_sections(path.parent)
    resolved: List[Dict[str, str]] = []
    for i, entry in enumerate(data["sections"]):
        if not isinstance(entry, dict):
            raise TemplateError(f"{path}: sections[{i}] must be a map")
        if "include" in entry:
            name = str(entry["include"])
            if name not in common:
                raise TemplateError(f"{path}: sections[{i}] includes unknown common section '{name}'")
            resolved.append(dict(common[name]))
        elif "body" in entry:
            resolved.append({"title": str(entry.get("title", "")), "body": str(entry["body"])})
        else:
            raise TemplateError(f"{path}: sections[{i}] needs either 'include' or 'title'+'body'")
    data["sections"] = resolved
    return data


def load_all_templates(base: Optional[Path] = None) -> List[Dict[str, Any]]:
    base = base or templates_dir()
    common = load_common_sections(base)
    templates = []
    for path in sorted(base.glob("*.yaml")):
        if path.name == "common-sections.yaml":
            continue
        templates.append(load_template(path, common))
    return templates


# ---------------------------------------------------------------------------
# Model resolution per harness
# ---------------------------------------------------------------------------

# OpenCode wants "provider/model-id"; map our provider names to its prefixes.
_OPENCODE_PROVIDER_PREFIX = {
    "ollama": "ollama",
    "claude": "anthropic",
    "copilot": "github-copilot",
}


def resolve_harness_models(target_root: Optional[Path] = None) -> Dict[str, Dict[str, str]]:
    """Return {harness: {level_N: model-string-in-that-harness's-dialect}}.

    claude   -> model CLASS (haiku/sonnet/opus) from active-models.json, since
                Claude Code accepts class aliases and that keeps files stable.
    opencode -> "provider/model-id" resolved through harness_models.
    copilot  -> bare model id resolved through harness_models.
    """
    from dftracer_agents.harness_models import (
        LEVELS,
        load_active_config,
        resolve_models,
    )

    config = load_active_config(target_root=target_root)
    resolved = resolve_models(config, target_root=target_root)
    out: Dict[str, Dict[str, str]] = {}

    claude_cfg = config.get("harnesses", {}).get("claude", {})
    class_by_level = claude_cfg.get("class_by_level", {}) if isinstance(claude_cfg, dict) else {}
    out["claude"] = {
        level: str(class_by_level.get(level) or {"level_1": "haiku", "level_2": "sonnet",
                                                 "level_3": "sonnet", "level_4": "opus"}[level])
        for level in LEVELS
    }

    oc = resolved.get("opencode", {})
    prefix = _OPENCODE_PROVIDER_PREFIX.get(str(oc.get("provider", "ollama")), str(oc.get("provider", "ollama")))
    out["opencode"] = {level: f"{prefix}/{oc.get(level, 'UNRESOLVED')}" for level in LEVELS}

    cp = resolved.get("copilot", {})
    out["copilot"] = {level: str(cp.get(level, "UNRESOLVED")) for level in LEVELS}
    return out


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

def _body_markdown(template: Dict[str, Any]) -> str:
    parts = []
    for section in template["sections"]:
        title, body = section["title"], section["body"].rstrip("\n")
        parts.append(f"## {title}\n\n{body}" if title else body)
    return "\n\n".join(parts) + "\n"


def _frontmatter(fields: Dict[str, Any], harness: str) -> str:
    fm = yaml.safe_dump(fields, sort_keys=False, allow_unicode=True, width=100)
    return f"---\n{GEN_MARKER_FMT.format(harness=harness)}\n{fm}---\n\n"


def _skill_preamble(template: Dict[str, Any]) -> str:
    """For harnesses without a ``skills:`` frontmatter key, tell the agent to
    locate what it needs in its skills via the knowledge graph instead of a
    blanket load.

    ``graph_query(mode="docs", ...)`` indexes this repo's own skills/agent
    definitions as markdown nodes (headings + file:line), so the agent can find
    the specific section it needs and read only that slice — the same
    locate-before-you-read discipline used for source code, applied to skills
    too. A full read of the skill file is still fine when the agent genuinely
    needs the whole document (e.g. an exhaustive checklist walk).
    """
    skills = template.get("skills") or []
    if not skills:
        return ""
    joined = ", ".join(skills)
    return (
        "## Locate your skills via the graph first (MANDATORY)\n\n"
        f"This agent's skills are: {joined}. Before anything else, for the SPECIFIC "
        "rule/section you need, query the graph instead of loading the whole skill:\n\n"
        "```\ngraph_query(mode=\"docs\", question=\"<topic within one of your skills>\")"
        "  # -> file:line\n```\n\n"
        "Then open only that file:line range. Read/`session_read_file` the whole "
        "skill only when you genuinely need the entire document (e.g. an exhaustive "
        "checklist that deliberately needs every category).\n\n"
    )


# ---------------------------------------------------------------------------
# Converters — one per harness
# ---------------------------------------------------------------------------

def render_claude(template: Dict[str, Any], level_models: Dict[str, str]) -> str:
    fields: Dict[str, Any] = {
        "name": template["name"],
        "description": template["description"],
        "model": level_models.get(template["model_level"], "sonnet"),
        "model_level": template["model_level"],
    }
    if template.get("effort"):
        fields["effort"] = template["effort"]
    if template.get("isolation"):
        fields["isolation"] = template["isolation"]
    if template.get("tools"):
        fields["tools"] = ", ".join(template["tools"])
    if template.get("skills"):
        fields["skills"] = ", ".join(template["skills"])
    return _frontmatter(fields, "claude") + _body_markdown(template)


def _opencode_tool_name(tool: str) -> str:
    m = _MCP_RE.match(tool)
    if m:
        return f"{m.group(1)}_{m.group(2)}"  # mcp__dftracer__analyze -> dftracer_analyze
    return _OPENCODE_BUILTIN.get(tool, tool.lower())


def render_opencode(template: Dict[str, Any], level_models: Dict[str, str]) -> str:
    fields: Dict[str, Any] = {
        "description": template["description"],
        "mode": "subagent",
        "model": level_models.get(template["model_level"], "UNRESOLVED"),
    }
    if template.get("tools"):
        # Allowlist semantics: everything off, then the listed tools on.
        tools_map: Dict[str, bool] = {"*": False}
        for tool in template["tools"]:
            tools_map[_opencode_tool_name(tool)] = True
        fields["tools"] = tools_map
    return _frontmatter(fields, "opencode") + _skill_preamble(template) + _body_markdown(template)


def _copilot_tool_name(tool: str) -> str:
    m = _MCP_RE.match(tool)
    if m:
        return f"{m.group(1)}/{m.group(2)}"  # mcp__dftracer__analyze -> dftracer/analyze
    return _COPILOT_BUILTIN.get(tool, tool.lower())


def render_copilot(template: Dict[str, Any], level_models: Dict[str, str]) -> str:
    fields: Dict[str, Any] = {
        "name": template["name"],
        "description": template["description"],
    }
    model = level_models.get(template["model_level"])
    if model and model != "UNRESOLVED":
        fields["model"] = model
    if template.get("tools"):
        seen: List[str] = []
        for tool in template["tools"]:
            mapped = _copilot_tool_name(tool)
            if mapped not in seen:
                seen.append(mapped)
        fields["tools"] = seen
    return _frontmatter(fields, "copilot") + _skill_preamble(template) + _body_markdown(template)


RENDERERS = {
    "claude": render_claude,
    "opencode": render_opencode,
    "copilot": render_copilot,
}


def render_all(
    target_root: Optional[Path] = None,
    harnesses: Optional[List[str]] = None,
    base: Optional[Path] = None,
) -> Dict[str, Dict[str, str]]:
    """Render every template for every harness.

    Returns {harness: {relative_output_path: content}} without writing anything;
    the installer (dftracer_agents.agents) owns the filesystem side.
    """
    templates = load_all_templates(base)
    models = resolve_harness_models(target_root)
    out: Dict[str, Dict[str, str]] = {}
    for harness in harnesses or list(HARNESSES):
        subdir, pattern = HARNESS_OUTPUT[harness]
        renderer = RENDERERS[harness]
        files: Dict[str, str] = {}
        for template in templates:
            rel = f"{subdir}/{pattern.format(name=template['name'])}"
            files[rel] = renderer(template, models[harness])
        out[harness] = files
    return out
