# External/user-facing
base_run_dir: "$LUSTRE_ROOT/workspaces/scaffold/s7opt/runs"
dataset_dir: "$LUSTRE_ROOT/workspaces/scaffold/s7opt/datasets"
fract_base_dir: "$LUSTRE_ROOT/workspaces/scaffold/fractals"
n_categories: 5                    # Number of fractal categories present in the dataset.
n_instances_used_per_fractal: 100
problem_scale: 7
unet_bottleneck_dim: 3             # Power of 2 of the unet bottleneck layer dimension. Default of 3 -> bottleneck layer of size 8.
seed: 42                           # Random seed.
batch_size: 1                      # Batch sizes for each vol size per rank.
dataloader_num_workers: 24
optimizer: "ADAM"                  # "ADAM" is preferred option, otherwise training defautls to RMSProp.
dc_num_shards: [1, 1, 1]           # DistConv param: number of shards to divide the tensor into. It's best to choose the fewest ranks needed to fit one sample in GPU memory, since that keeps communication at a minimum
dc_shard_dims: [2, 3, 4]           # DistConv param: dimension on which to shard
checkpoint_interval: -1            # Checkpoint every C epochs; set to -1 to disable checkpointing entirely.

# Internal/dev use only
variance_threshold: 0.15           # Variance threshold for valid fractals. Default is 0.15.
n_fracts_per_vol: 3                # Number of fractals overlaid in each volume. Default is 3.
val_split: 30                      # In percent.
epochs: 3
starting_learning_rate: 0.001      # Initial learning rate for training.
min_learning_rate: 0.0001          # Minimum learning rate for CosineAnnealingWarmRestarts.
T_0: 100                           # Epochs in the first cosine restart cycle.
T_mult: 2                          # Restart cycle growth factor.
disable_scheduler: 0               # If 1, disable scheduler during training to use constant LR.
more_determinism: 0                # If 1, improve model training determinism.
datagen_from_scratch: 0            # If 1, delete existing fractals and instances, then regenerate from scratch.
train_from_scratch: 1              # If 1, delete existing train stats and checkpoint files. Keep 0 if want to restart runs where we left off.
dist: 1                            # If 1, use torch DDP.
torch_amp: 1                       # If 1, use mixed precision in training.
framework: "torch"                 # The DL framework to train with. Only valid option for now is "torch".
checkpoint_dir: "checkpoints"      # Subfolder in which to save training checkpoints.
loss_freq: 1                       # Number of epochs between logging the overall loss.
normalize: 1                       # Cateogry search normalization parameter
group_norm_groups: 8              # Number of groups used by GroupNorm in the UNet blocks.
warmup_batches: 2
ce_weight_sample_fraction: 0.1     # Fraction of training masks to sample when estimating background vs foreground CE weights.
dataset_reuse_enforce_commit_id: 0 # Enforce matching commit IDs for dataset reuse.
target_dice: 0.95
